logging:
  level:
    "com.lobox" : DEBUG

rocksdb:
  dataDir: "/media/mushtu/New Volume1/lobox/rocksdb/data"
  createIfMissing: true
  dbWriteBufferSize: 536870912 # 512 MB
  targetFileSizeBase: 268435456 # 256 MB

application:
  datasetBatchImportSize: 250000 # number of records to index in batch
  datasets:
    title-principals-tsv: "/media/mushtu/New Volume1/ImdbDataSet/title.principals.tsv"
    title-basics-tsv: "/media/mushtu/New Volume1/ImdbDataSet/title.basics.tsv"
    title-crew-tsv: "/media/mushtu/New Volume1/ImdbDataSet/title.crew.tsv"
    name-basics-tsv: "/media/mushtu/New Volume1/ImdbDataSet/name.basics.tsv"